# This ZFS-specific config enables Atuin's daemon mode to work around
# the performance issues between ZFS and SQLite.
# See https://github.com/atuinsh/atuin/issues/952
#
# In configs/shell/30_misc.sh, we detect if the Atuin daemon is running
# and set ATUIN_CONFIG_DIR to point to this file only when needed.
# Run scripts/setup-atuin-daemon.sh on ZFS systems to set up the daemon.

## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checks
update_check = false

#TODO: 
## address of the sync server
#sync_address = "https://atuin.lab.nijho.lt"
enter_accept = true

[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
 "git",
 "g",
 "uv",
]

[theme]
name = "autumn"

# Enable the Atuin daemon to solve ZFS/SQLite performance issues.
# The daemon takes database writes off the critical path, preventing
# the 5+ second hangs that occur with direct SQLite access on ZFS.
# See: https://github.com/atuinsh/atuin/issues/952
[daemon]
enabled = true
